name: khalti_sdk
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  intl: ^0.17.0
  khalti: ^1.0.2
  url_launcher: ^6.1.5

dev_dependencies:
#  flutter_lints: ^1.0.4

flutter:
  assets:
    - assets/payment/
    - assets/error/
    - assets/logo/
    - assets/dialog/